(function(){
  'use strict';
  const G=window.SlopInTime,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),engine=G.createEngine({seed:GameSlopKit.parseSeed(params.get('seed'))}),renderer=G.createRenderer($('game')),audio=G.createAudio();
  const cabinet=document.querySelector('.cabinet'),keyboard=new Set(),touch=new Map(),pad=new Set(),contacts=new Map();let stickId=null,players=1,previousStatus='',last=0,accumulator=0,padPause=false,best=0,posted=false;
  const keymap={ArrowLeft:'0:left',ArrowRight:'0:right',ArrowUp:'0:up',ArrowDown:'0:down',KeyX:'0:attack',KeyZ:'0:jump',Space:'0:jump',KeyC:'0:special',KeyA:'1:left',KeyD:'1:right',KeyW:'1:up',KeyS:'1:down',KeyH:'1:attack',KeyG:'1:jump',KeyJ:'1:special'};
  function bestKey(){return 'gameslop:slop-in-time:'+engine.state.difficulty+':'+players+':best';}
  function storageGet(key){try{return Number(localStorage.getItem(key))||0;}catch(_){return 0;}}
  function sync(){const held=new Set([...keyboard,...pad,...[...touch.values()].flat()]);for(let i=0;i<engine.state.players.length;i++)for(const a of ['left','right','up','down','attack','jump','special'])engine.input(i,a,held.has(i+':'+a));}
  function releasePointer(id){const node=contacts.get(id);if(!node)return;contacts.delete(id);touch.delete(id);node.classList.toggle('pressed',[...contacts.values()].includes(node));if(stickId===id){stickId=null;$('stick').style.setProperty('--sx','0px');$('stick').style.setProperty('--sy','0px');}if(node.hasPointerCapture?.(id))try{node.releasePointerCapture(id);}catch(_){}sync();}
  function clearInput(){keyboard.clear();pad.clear();touch.clear();[...contacts.keys()].forEach(releasePointer);engine.release();}
  function start(){clearInput();audio.unlock();engine.start({players,difficulty:$('difficulty').value});best=storageGet(bestKey());posted=false;$('game').focus({preventScroll:true});update();}
  function pause(){clearInput();engine.pause();update();}
  function resume(){clearInput();audio.unlock();if(engine.state.status==='paused')engine.pause();else if(engine.state.status==='clear')engine.advance();else if(engine.state.status==='gameover'&&engine.state.continues>0)engine.continueRun();else start();update();$('game').focus({preventScroll:true});}
  function update(){
    const s=engine.state;audio.update(s,engine.drainEvents());$('title-screen').hidden=s.status!=='ready';$('overlay').hidden=!['paused','clear','gameover','victory'].includes(s.status);$('pause').disabled=!['playing','paused'].includes(s.status);$('pause').textContent=s.status==='paused'?'RESUME':'PAUSE';$('pause').setAttribute('aria-label',s.status==='paused'?'Resume game':'Pause game');$('era-number').textContent=String(s.stage+1).padStart(2,'0');$('era-name').textContent=G.stages[s.stage].name.toUpperCase();$('status').textContent=s.status==='ready'?'READY TO MAKE HISTORY.':s.status==='playing'?s.arena?'CLEAR THE STREET.':'KEEP MOVING →':s.status.toUpperCase();$('best').textContent=String(Math.max(s.score,best)).padStart(7,'0');
    const energy=s.players[0]?.energy||0,special=document.querySelector('[data-action=special]');special.disabled=energy<100;special.classList.toggle('charged',energy>=100);$('special-charge').textContent=energy>=100?'READY':Math.floor(energy)+'%';
    if(previousStatus!==s.status){
      if(['clear','gameover','victory'].includes(s.status)&&s.score>best){best=s.score;try{localStorage.setItem(bestKey(),String(best));}catch(_){}}
      const data={paused:['TIME OUT','TAKE A BREATHER','The timeline can wait.\nYour fight resumes right here.','BACK TO THE FIGHT →'],clear:['ERA '+(s.stage+1)+' SECURED',s.stage===5?'TIME’S UP.':'HISTORY, HANDLED.',G.stages[s.stage].boss+' defeated.\n'+s.score.toLocaleString()+' points · Best combo: '+s.bestCombo,s.stage===5?'RESTORE THE TIMELINE →':'NEXT ERA →'],gameover:['OUT OF TIME','DOWN, NOT OUT.',s.score.toLocaleString()+' points · '+s.continues+' continues remaining',s.continues?'CONTINUE THIS ERA →':'TRY AGAIN →'],victory:['THE TIMELINE IS YOURS','SLOP SAVES TOMORROW.',s.score.toLocaleString()+' points · '+s.kills+' knockouts\nBest combo: '+s.bestCombo+' · All six eras restored.','RUN IT BACK →']}[s.status];
      if(data){$('overlay-kicker').textContent=data[0];$('overlay-title').textContent=data[1];$('overlay-body').textContent=data[2];$('resume').textContent=data[3];$('resume').focus({preventScroll:true});}
      if(['gameover','victory'].includes(s.status)&&!posted){posted=true;if(parent!==window)parent.postMessage({v:1,type:'gameover',game:'slop-in-time',skin:'gameslop',score:s.score,seed:s.seed,inputsHash:engine.hash(),stats:{stage:s.stage+1,kills:s.kills,bestCombo:s.bestCombo,victory:s.status==='victory'}},'*');}if(s.status==='playing')posted=false;
      previousStatus=s.status;
    }
  }
  $('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('resume').addEventListener('click',resume);$('restart').addEventListener('click',()=>{clearInput();engine.state.status='ready';engine.state.stage=0;engine.state.camera=0;update();});
  $('sound').addEventListener('click',()=>{audio.toggle();$('sound').textContent=audio.muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-pressed',String(audio.muted));});$('sound').textContent=audio.muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-pressed',String(audio.muted));
  document.querySelectorAll('[data-players]').forEach(button=>button.addEventListener('click',()=>{players=Number(button.dataset.players);document.querySelectorAll('[data-players]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));});}));
  document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'&&e.target.tagName==='BUTTON')return;const action=keymap[e.code];if(action){e.preventDefault();keyboard.add(action);sync();}if(!e.repeat){if(e.code==='KeyP'||e.code==='Escape'){e.preventDefault();pause();}if(e.code==='Enter'&&e.target.tagName!=='BUTTON'){if(engine.state.status==='ready')start();else if(engine.state.status!=='playing')resume();}}});
  document.addEventListener('keyup',e=>{if(keymap[e.code]){e.preventDefault();keyboard.delete(keymap[e.code]);sync();}});
  function steer(e){const r=$('stick').getBoundingClientRect();let x=(e.clientX-r.x-r.width/2)/(r.width/2),y=(e.clientY-r.y-r.height/2)/(r.height/2);const length=Math.max(1,Math.hypot(x,y));x/=length;y/=length;const actions=[];if(Math.abs(x)>.23)actions.push('0:'+(x<0?'left':'right'));if(Math.abs(y)>.23)actions.push('0:'+(y<0?'up':'down'));$('stick').style.setProperty('--sx',x*32+'px');$('stick').style.setProperty('--sy',y*32+'px');touch.set(e.pointerId,actions);sync();}
  function capture(node,id){contacts.set(id,node);try{node.setPointerCapture(id);}catch(_){}}
  $('stick').addEventListener('pointerdown',e=>{e.preventDefault();if(engine.state.status!=='playing'||stickId!==null)return;audio.unlock();stickId=e.pointerId;capture($('stick'),e.pointerId);steer(e);});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickId){e.preventDefault();steer(e);}});
  document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('pointerdown',e=>{e.preventDefault();if(engine.state.status!=='playing'||button.disabled)return;audio.unlock();capture(button,e.pointerId);button.classList.add('pressed');touch.set(e.pointerId,['0:'+button.dataset.action]);sync();}));
  for(const event of ['pointerup','pointercancel','lostpointercapture'])$('touch').addEventListener(event,e=>releasePointer(e.pointerId));$('touch').addEventListener('contextmenu',e=>e.preventDefault());
  const secondaryTaps=new WeakMap(),menuButton=e=>e.target.closest?.('#pause,#sound,#fullscreen');cabinet.addEventListener('pointerdown',e=>{const b=menuButton(e);if(b)secondaryTaps.delete(b);},true);cabinet.addEventListener('pointerup',e=>{const b=menuButton(e);if(!b||b.disabled||e.pointerType!=='touch'||e.isPrimary)return;const r=b.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;secondaryTaps.set(b,{id:e.pointerId,time:performance.now()});b.click();});cabinet.addEventListener('click',e=>{const b=menuButton(e),tap=b&&secondaryTaps.get(b);if(tap&&e.isTrusted&&e.detail>0&&performance.now()-tap.time<500&&(e.pointerId===undefined||e.pointerId===tap.id)){e.preventDefault();e.stopImmediatePropagation();secondaryTaps.delete(b);}},true);
  function backgroundPause(){clearInput();if(engine.state.status==='playing')engine.pause();update();}window.addEventListener('blur',backgroundPause);document.addEventListener('visibilitychange',()=>{if(document.hidden)backgroundPause();});window.addEventListener('resize',clearInput);screen.orientation?.addEventListener?.('change',clearInput);
  function expanded(){return !!document.fullscreenElement||cabinet.classList.contains('expanded');}function fullscreenUI(){const on=expanded();$('fullscreen').textContent=on?'EXIT':'EXPAND';document.body.classList.toggle('expanded',on);}
  $('fullscreen').addEventListener('click',async()=>{clearInput();try{if(document.fullscreenElement)await document.exitFullscreen();else if(cabinet.classList.contains('expanded'))cabinet.classList.remove('expanded');else{try{if(!cabinet.requestFullscreen)throw Error('fallback');await cabinet.requestFullscreen();}catch(_){cabinet.classList.add('expanded');}try{await screen.orientation?.lock?.('landscape');}catch(_){}}}catch(_){}if(!expanded())try{screen.orientation?.unlock?.();}catch(_){}fullscreenUI();});document.addEventListener('fullscreenchange',fullscreenUI);
  function gamepads(){pad.clear();let startDown=false;const pads=navigator.getGamepads?Array.from(navigator.getGamepads()).filter(Boolean).slice(0,2):[];pads.forEach((g,i)=>{const b=n=>!!g.buttons[n]?.pressed;const actions={left:b(14)||g.axes[0]<-.3,right:b(15)||g.axes[0]>.3,up:b(12)||g.axes[1]<-.3,down:b(13)||g.axes[1]>.3,attack:b(2)||b(7),jump:b(0)||b(1),special:b(3)};Object.entries(actions).forEach(([a,on])=>{if(on)pad.add(i+':'+a);});startDown||=b(9);});if(startDown&&!padPause){if(engine.state.status==='ready')start();else if(['playing','paused'].includes(engine.state.status))pause();else resume();}padPause=startDown;}
  function frame(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;gamepads();sync();if(engine.state.status==='playing'){accumulator+=dt;while(accumulator>=G.STEP){engine.tick();accumulator-=G.STEP;}}else accumulator=0;update();renderer.draw(engine.state,now/1000);requestAnimationFrame(frame);}
  if(params.get('debug')==='1')window.__gameslop={engine,renderer,audio,touch:{inspect:()=>({contacts:contacts.size,stickId})}};
  document.body.dataset.ready='1';update();requestAnimationFrame(frame);
})();
