'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createEngine,stages,STEP}=require('../js/engine');
const tick=(e,n)=>{for(let i=0;i<n;i++)e.tick();};
function arena(options={}){const e=createEngine({seed:42});e.start(options);e.state.players[0].x=160;e.tick();e.state.props=[];e.state.pickups=[];e.state.traps=[];e.state.enemies=e.state.enemies.slice(0,1);const foe=e.state.enemies[0];Object.assign(foe,{entrance:null,kind:'grunt',x:225,y:416,hp:200,maxHp:200,cooldown:100,stun:0,down:0});e.state.players[0].invincible=100;return {e,p:e.state.players[0],foe};}
test('six eras each have a distinct theme, boss, and collectible weapon',()=>{assert.equal(stages.length,6);for(const key of ['theme','boss','weapon'])assert.equal(new Set(stages.map(s=>s[key])).size,6);});
test('start and restart honor difficulty, co-op and a reproducible seed',()=>{const e=createEngine({seed:17});e.start({players:2,difficulty:'hard'});assert.equal(e.state.players.length,2);assert.equal(e.state.players[0].lives,2);e.state.score=999;e.start({difficulty:'easy'});assert.equal(e.state.score,0);assert.equal(e.state.players[0].lives,5);});
test('movement uses a bounded ground plane without treating up as climbing',()=>{const {e,p}=arena();e.input(0,'up',true);tick(e,150);assert.equal(p.y,335);assert.equal(p.z,0);e.input(0,'up',false);e.input(0,'down',true);tick(e,150);assert.equal(p.y,487);assert.equal(p.z,0);});
test('Jump alone rises higher than 150 pixels, never attacks, and lands',()=>{const {e,p,foe}=arena();e.input(0,'jump',true);e.input(0,'jump',false);tick(e,30);assert.ok(p.z>150);assert.equal(foe.hp,200);assert.equal(p.action,null);tick(e,50);assert.equal(p.z,0);assert.equal(p.vz,0);});
test('pressing Attack after takeoff produces a real jump kick',()=>{const {e,p,foe}=arena();e.input(0,'jump',true);tick(e,3);e.input(0,'jump',false);e.input(0,'attack',true);tick(e,8);assert.equal(p.action.kind,'kick');assert.equal(foe.hp,178);});
test('holding Jump cannot repeatedly hop after landing',()=>{const {e,p}=arena();e.input(0,'jump',true);tick(e,150);assert.equal(p.z,0);assert.equal(e.drainEvents().filter(x=>x.type==='jump').length,1);});
test('held Attack chains three hits with a finishing knockdown, not per-frame damage',()=>{const {e,p,foe}=arena();e.input(0,'attack',true);tick(e,50);assert.equal(p.comboStep,3);assert.equal(foe.hp,156);assert.ok(foe.down>0);assert.equal(e.state.combo,3);});
test('attacks miss enemies in another depth lane',()=>{const {e,foe}=arena();foe.y=480;e.input(0,'attack',true);tick(e,8);assert.equal(foe.hp,200);});
test('a vulnerable close enemy is thrown and damages another even if the throw kills it',()=>{const {e,p,foe}=arena();foe.x=p.x+25;foe.hp=15;const other={...foe,id:999,x:p.x+95,hp:100,maxHp:100,throwHits:[]};e.state.enemies.push(other);e.input(0,'attack',true);tick(e,18);assert.ok(foe.hp<=0);assert.ok(other.hp<100);assert.ok(e.drainEvents().some(x=>x.type==='throw'));});
test('bosses cannot be grabbed and thrown',()=>{const {e,p,foe}=arena();foe.boss=true;foe.hp=15;foe.x=p.x+25;e.input(0,'attack',true);tick(e,8);assert.ok(!e.drainEvents().some(x=>x.type==='throw'));});
test('boss windups survive player combos and still resolve an attack',()=>{const {e,p,foe}=arena();p.invincible=0;foe.boss=true;foe.x=p.x+45;foe.cooldown=0;e.input(0,'attack',true);tick(e,70);assert.ok(p.hp<100);assert.ok(foe.hp<200);});
test('special requires charge, hits its area and is consumed once per press',()=>{const {e,p,foe}=arena();p.energy=99;e.input(0,'special',true);tick(e,1);assert.equal(foe.hp,200);e.input(0,'special',false);p.energy=100;e.input(0,'special',true);tick(e,15);assert.equal(foe.hp,158);assert.ok(p.energy<100);assert.equal(e.drainEvents().filter(x=>x.type==='special').length,1);});
test('breakable props yield actual healing and weapon pickups with limited durability',()=>{const {e,p}=arena();e.state.props=[{id:20,x:p.x+40,y:p.y,hp:10,kind:'food'}];e.input(0,'attack',true);tick(e,8);assert.equal(e.state.props[0].hp<=0,true);assert.equal(e.state.pickups.length,1);e.input(0,'attack',false);p.hp=50;p.x+=40;tick(e,5);assert.equal(p.hp,85);e.state.pickups=[{x:p.x,y:p.y,kind:'weapon'}];tick(e,1);assert.equal(p.weapon,stages[0].weapon);assert.equal(p.weaponHits,22);});
test('enemy windup is visible before damage, and a jump dodges a ground strike',()=>{const {e,p,foe}=arena();p.invincible=0;foe.cooldown=0;foe.x=p.x+45;tick(e,1);assert.ok(foe.windup>0);assert.equal(p.hp,100);e.input(0,'jump',true);tick(e,30);assert.equal(p.hp,100);});
test('taking damage respawns locally, exhausted lives lead to gameover, continues are limited',()=>{const {e,p,foe}=arena();p.lives=1;p.hp=1;p.invincible=0;foe.x=p.x+45;foe.cooldown=0;tick(e,125);assert.equal(e.state.status,'gameover');assert.equal(p.lives,0);e.continueRun();assert.equal(e.state.status,'playing');assert.equal(e.state.continues,1);assert.equal(p.hp,100);e.state.status='gameover';e.continueRun();e.state.status='gameover';e.continueRun();assert.equal(e.state.status,'gameover');assert.equal(e.state.continues,0);});
test('pause clears pending input and freezes all combat state',()=>{const {e,p}=arena();e.input(0,'jump',true);e.pause();const before=JSON.stringify(e.state);tick(e,50);assert.equal(JSON.stringify(e.state),before);e.pause();tick(e,1);assert.equal(p.z,0);});
test('one co-op player can be out while the other continues fighting',()=>{const {e,p}=arena({players:2});p.lives=0;p.dead=0;tick(e,1);assert.equal(e.state.status,'playing');assert.equal(e.state.players[1].hp,100);});
test('sixty locked encounters with variable waves and six delayed boss endings reach victory',()=>{const e=createEngine();e.start();let bosses=0,multi=0;for(let stage=0;stage<6;stage++){for(let gate=0;gate<10;gate++){const p=e.state.players[0];p.x=stages[stage].encounters[gate]-300;p.y=416+require('../js/content').floor(stages[stage],p.x);e.state.camera=Math.max(0,p.x-310);e.state.cameraY=require('../js/content').floor(stages[stage],p.x);e.tick();assert.equal(e.state.arena,true);if(e.state.waveCount>1)multi++;bosses+=e.state.enemies.filter(x=>x.boss).length;for(let frame=0;frame<500&&e.state.gate===gate;frame++){e.state.enemies.forEach(x=>{x.hp=0;});e.tick();}assert.equal(e.state.gate,gate+1);}assert.equal(e.state.status,'clear');e.advance();}assert.equal(bosses,6);assert.ok(multi>5&&multi<50);assert.equal(e.state.status,'victory');});
test('all six eras can be fought to victory with real inputs and finite player health',()=>{const e=createEngine({seed:5});e.start({difficulty:'normal'});for(let i=0;i<300000&&e.state.status!=='victory';i++){
  if(e.state.status==='clear'){e.advance();continue;}if(e.state.status==='gameover'){if(!e.state.continues)break;e.continueRun();continue;}
  const p=e.state.players[0],enemies=e.state.enemies.filter(x=>x.hp>0&&!x.entrance),target=enemies.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];
  const turn=require('../js/content').nextTurn(stages[e.state.stage],p);const dx=target?target.x-p.x:100,dy=target?target.y-p.y:416+require('../js/content').floor(stages[e.state.stage],p.x+65)-p.y;
  e.input(0,'right',dx>25);e.input(0,'left',dx< -25);e.input(0,'up',dy< -8);e.input(0,'down',dy>8);e.input(0,'attack',!!target&&(Math.sign(dx)===p.face||Math.abs(dx)<8));e.input(0,'jump',!!target&&i%70===0);e.input(0,'special',p.energy>=100&&!!target);e.tick();
}assert.equal(e.state.status,'victory',JSON.stringify({status:e.state.status,gate:e.state.gate,player:e.state.players[0],enemies:e.state.enemies}));assert.ok(e.state.kills>=90);});
test('identical seed and input sequence reproduce combat results',()=>{function run(){const e=createEngine({seed:7});e.start();for(let i=0;i<900;i++){e.input(0,'right',i<150);e.input(0,'attack',i>90);e.input(0,'jump',i%90===0);e.tick(STEP);}return {score:e.state.score,players:e.state.players,enemies:e.state.enemies,hash:e.hash()};}assert.deepEqual(run(),run());});

test('every route exceeds Commando length with varied encounter spacing and seven landmarks',()=>{
  for(const s of stages){assert.ok(s.width>6600);assert.equal(s.encounters.length,10);assert.equal(s.landmarks.length,7);assert.equal(new Set(s.landmarks).size,7);assert.ok(new Set(s.encounters.slice(1).map((x,i)=>x-s.encounters[i])).size>3);assert.ok(s.encounters.at(-1)+350<s.width);}
});
test('a continue resumes at the latest supply checkpoint with clean combat state',()=>{
  const e=createEngine();e.start();const p=e.state.players[0];e.state.gate=2;p.x=stages[0].encounters[2]-300;e.state.camera=p.x-310;p.y=416+require('../js/content').floor(stages[0],p.x);e.state.cameraY=p.y-416;e.tick();p.hp=30;
  for(let i=0;i<300&&e.state.gate===2;i++){e.state.enemies=[];e.tick();}assert.equal(e.state.checkpoint,3);assert.equal(p.hp,75);
  e.state.status='gameover';e.state.hazards=[{kind:'steam'}];e.continueRun();assert.equal(e.state.gate,3);assert.equal(e.state.hazards.length,0);assert.equal(p.hp,100);assert.ok(p.x>2000);assert.ok(e.state.camera>0);assert.ok(e.state.props.every(prop=>prop.x>=p.x));
});
function bossFixture(index){const e=createEngine();e.start();for(let i=0;i<index;i++){e.state.status='clear';e.advance();}e.state.gate=9;const p=e.state.players[0];p.x=stages[index].encounters[9]-300;p.y=416+require('../js/content').floor(stages[index],p.x);e.state.cameraY=require('../js/content').floor(stages[index],p.x);e.state.camera=p.x-310;p.invincible=100;e.tick();const boss=e.state.enemies.find(x=>x.boss);e.state.enemies=[boss];Object.assign(boss,{x:boss.entrance.landX,y:boss.entrance.landY,z:0,entrance:null});boss.superTimer=0;boss.cooldown=0;return {e,p,boss};}
test('each boss telegraphs a distinct superpower that resolves even from across the arena',()=>{
  const kinds=[];for(let stage=0;stage<6;stage++){const {e,p,boss}=bossFixture(stage);e.tick();assert.equal(boss.attack.kind,'super');assert.ok(boss.windup>=1);assert.equal(e.state.hazards.length,0);tick(e,67);assert.ok(e.state.hazards.length>=2);assert.ok(e.state.hazards.every(h=>h.delay>0));assert.equal(p.hp,100);kinds.push(e.state.hazards[0].kind);boss.hp=0;e.tick();assert.equal(e.state.hazards.length,0);}assert.equal(new Set(kinds).size,6);
});
test('red rage phase starts at thirty percent, persists and accelerates recovery',()=>{
  const {e,boss}=bossFixture(0);boss.superTimer=100;boss.cooldown=2;boss.hp=boss.maxHp*.31;e.tick();assert.equal(boss.enraged,false);boss.hp=boss.maxHp*.3;e.tick();assert.equal(boss.enraged,true);assert.ok(boss.superTimer<=1);assert.equal(e.drainEvents().filter(x=>x.type==='enrage').length,1);const before=boss.cooldown;e.tick();assert.ok(before-boss.cooldown>STEP);assert.equal(e.drainEvents().filter(x=>x.type==='enrage').length,0);
});
test('superpower damage respects warnings, depth, jumping and player invulnerability',()=>{
  for(const stage of [0,1,2,3,4,5]){const {e,p,boss}=bossFixture(stage);e.tick();tick(e,67);boss.cooldown=100;boss.windup=0;boss.attack=null;boss.superTimer=100;
    const h=e.state.hazards[0];e.state.hazards=[h];h.delay=0;h.vx=0;if(h.kind==='time'){p.x=h.x+29;p.y=h.y;}else{p.x=h.x;p.y=h.y;}p.invincible=0;p.z=0;e.tick();assert.ok(p.hp<100,'damage '+h.kind);const hp=p.hp;e.tick();assert.equal(p.hp,hp,'invulnerability '+h.kind);
  }
  const {e,p,boss}=bossFixture(2);e.tick();tick(e,67);boss.cooldown=100;const h=e.state.hazards[0];e.state.hazards=[h];h.delay=0;h.vx=0;p.x=h.x;p.y=h.y;p.invincible=0;p.z=70;p.vz=0;e.tick();assert.equal(p.hp,100,'jump dodges quake');
});
test('distinct diagonal routes can be traversed with movement and stay on their visible floor',()=>{
 const C=require('../js/content');assert.equal(new Set(stages.map(s=>JSON.stringify(s.turns))).size,6);
 for(let index=0;index<6;index++){const e=createEngine();e.start();for(let j=0;j<index;j++){e.state.status='clear';e.advance();}const p=e.state.players[0];e.state.gate=9;e.state.pickups=[];e.state.props=[];e.state.traps=[];
 for(const t of stages[index].turns){e.release();e.state.arena=false;e.state.enemies=[];p.x=t.x-10;p.y=411+C.floor(stages[index],p.x);e.state.camera=p.x-310;
 for(let n=0;n<600&&p.x<t.end+60;n++){const desired=411+C.floor(stages[index],p.x+45);e.input(0,'right',true);e.input(0,'down',p.y<desired-4);e.input(0,'up',p.y>desired+4);e.tick();assert.ok(C.walkable(stages[index],p.x,p.y));}assert.ok(p.x>t.end);assert.ok(e.state.cameraY>t.offset+t.drop-20);}
 }
});
test('manhole lid throws once, hits several enemies and leaves an open hole',()=>{
  const {e,p,foe}=arena();e.state.props=[{id:99,x:p.x,y:p.y,hp:1,kind:'lid',open:false}];foe.x=p.x+100;const other={...foe,id:100,x:p.x+180,throwHits:[]};e.state.enemies.push(other);e.input(0,'attack',true);tick(e,22);assert.equal(e.state.props[0].open,true);assert.equal(p.action.kind,'propThrow');assert.ok(foe.hp<=155);assert.ok(other.hp<=155);assert.equal(e.drainEvents().filter(x=>x.type==='throw').length,1);
});
test('shield guards block frontal jabs, but a finisher breaks their defense',()=>{
  const {e,foe}=arena();foe.kind='guard';foe.face=-1;e.input(0,'attack',true);tick(e,10);assert.equal(foe.hp,200);tick(e,40);assert.equal(foe.hp,180);assert.ok(foe.down>0);
});
test('flying enemies avoid ground punches and can be hit by an airborne attack',()=>{
  const {e,p,foe}=arena();foe.kind='flyer';foe.z=82;foe.cooldown=100;foe.stun=0;e.input(0,'attack',true);tick(e,7);assert.equal(foe.hp,200);e.input(0,'attack',false);p.cooldown=0;p.action=null;p.z=70;p.vz=0;foe.x=p.x+55;e.input(0,'attack',true);tick(e,7);assert.ok(foe.hp<200);
});
test('each era contains five themed enemies, varied traps, no story and two usable weapons',()=>{
  const C=require('../js/content');assert.equal(Object.keys(C.weapons).length,12);const e=createEngine();e.start();for(let i=0;i<6;i++){if(i){e.state.status='clear';e.advance();}assert.equal(stages[i].weapons.length,2);assert.equal(e.state.story,null);assert.equal(stages[i].enemies.length,5);assert.equal(new Set(stages[i].enemies.map(e=>e.kind)).size,5);assert.ok(e.state.traps.some(t=>t.kind===stages[i].trap));assert.ok(e.state.pickups.some(p=>p.kind==='weapon'&&p.weapon===stages[i].weapons[1]));assert.equal(e.state.props.filter(p=>p.kind==='lid').length,2);assert.ok(new Set(e.state.props.map(p=>p.kind)).size>=3);}
});
test('trap warnings are harmless; active ground traps can be jumped',()=>{
  const {e,p}=arena();const t={x:p.x,y:p.y,kind:'puddle',clock:2.5};e.state.traps=[t];p.invincible=0;e.state.time=2.5;e.tick();assert.ok(t.warning);assert.equal(p.hp,100);t.clock=3.4;p.z=90;p.vz=0;e.tick();assert.ok(t.active);assert.equal(p.hp,100);p.z=0;tick(e,5);assert.equal(p.hp,84);
});
test('all weapon pickups use their own reach, damage and durability',()=>{
  const C=require('../js/content');for(const [id,w] of Object.entries(C.weapons)){const {e,p,foe}=arena();e.state.pickups=[{x:p.x,y:p.y,kind:'weapon',weapon:id}];e.tick();assert.equal(p.weapon,id);assert.equal(p.weaponHits,w.hits);foe.x=p.x+w.reach-5;e.input(0,'attack',true);tick(e,7);assert.equal(foe.hp,200-w.damage);assert.equal(p.weaponHits,w.hits-1);}
});
test('co-op players cannot outrun the shared view during a downward connector',()=>{
  const e=createEngine();e.start({players:2});e.state.gate=9;e.state.enemies=[];e.state.arena=false;const t=stages[0].turns[0],p=e.state.players[0],q=e.state.players[1];p.x=q.x=t.x+80;p.y=q.y=416;e.state.camera=p.x-310;e.input(0,'down',true);tick(e,180);assert.ok(p.y-q.y<=300.01);assert.ok(p.y-e.state.cameraY<=490);assert.ok(q.y-e.state.cameraY>=170);e.input(0,'down',false);e.input(0,'right',true);tick(e,400);assert.ok(p.x-e.state.camera<=914);
});

test('food recovery, cartridge charge and one shared permanent HP upgrade per stage',()=>{
 const C=require('../js/content');for(const [food,item] of Object.entries(C.foods)){const {e,p}=arena();p.hp=10;e.state.pickups=[{kind:'food',food,x:p.x,y:p.y}];e.tick();assert.equal(p.hp,10+item.heal);}
 const {e,p}=arena({players:2});e.state.pickups=[{kind:'heart',x:p.x,y:p.y}];e.tick();for(const q of e.state.players){assert.equal(q.maxHp,101);assert.deepEqual(q.upgrades,[0]);}e.state.status='gameover';e.continueRun();assert.equal(p.hp,101);assert.equal(e.state.pickups.filter(i=>i.kind==='heart').length,0);e.state.status='clear';e.advance();assert.equal(p.maxHp,101);assert.equal(e.state.pickups.filter(i=>i.kind==='heart').length,1);p.energy=0;e.state.pickups=[{kind:'energy',x:p.x,y:p.y}];e.tick();assert.equal(p.energy,30);e.start();assert.equal(e.state.players[0].maxHp,100);
});
test('camera stays locked through reinforcement gaps and no difficulty exceeds six enemies',()=>{
 const counts=new Set(),kindCounts={};for(const difficulty of ['easy','normal','hard']){kindCounts[difficulty]={};for(let seed=1;seed<=60;seed++){const e=createEngine({seed});e.start({players:seed%2+1,difficulty});const p=e.state.players[0];p.x=180;e.tick();const camera=e.state.camera,y=e.state.cameraY;assert.ok(e.state.enemies.length<=6);counts.add(e.state.enemies.length);for(const n of e.state.enemies)kindCounts[difficulty][n.kind]=(kindCounts[difficulty][n.kind]||0)+1;e.input(0,'right',true);p.invincible=100;tick(e,150);assert.equal(e.state.camera,camera);assert.equal(e.state.cameraY,y);if(e.state.waveCount>1){e.state.enemies=[];tick(e,20);assert.equal(e.state.arena,true);assert.equal(e.state.camera,camera);tick(e,50);assert.ok(e.state.enemies.length>0&&e.state.enemies.length<=6);}}}assert.ok(counts.size>=4);assert.ok(kindCounts.hard.thrower>kindCounts.easy.thrower);assert.ok(kindCounts.easy.grunt>kindCounts.easy.thrower);
});
test('boss destruction freezes combat, plays explosions, fades slowly, then clears',()=>{const {e,p,boss}=bossFixture(0);boss.hp=1;boss.x=p.x+55;boss.y=p.y;boss.cooldown=100;boss.superTimer=100;e.input(0,'attack',true);tick(e,8);assert.ok(e.state.ending);assert.equal(e.state.status,'playing');const x=p.x;e.input(0,'right',true);tick(e,70);assert.equal(p.x,x);assert.ok(e.state.effects.some(f=>f.kind==='explosion'));assert.equal(e.state.ending.fade,0);e.pause();const age=e.state.ending.age;tick(e,40);assert.equal(e.state.ending.age,age);e.pause();tick(e,110);assert.ok(e.state.ending.fade>0&&e.state.ending.fade<1);assert.equal(e.state.status,'playing');tick(e,100);assert.equal(e.state.status,'clear');assert.equal(e.state.ending.fade,1);});
test('interactive barrels roll, gongs stun and switches disable nearby hazards',()=>{
 for(const kind of ['barrel','gong','switch']){const {e,p,foe}=arena();e.state.props=[{x:p.x+45,y:p.y,hp:10,kind}];e.state.traps=[{x:p.x+160,y:p.y,kind:'steam',phase:0}];foe.x=p.x+180;e.input(0,'attack',true);tick(e,8);if(kind==='barrel'){assert.ok(e.state.missiles.some(m=>m.kind==='barrel'));tick(e,30);assert.ok(foe.hp<200);}if(kind==='gong')assert.ok(foe.stun>1);if(kind==='switch')assert.equal(e.state.traps[0].disabled,true);}
});
test('projectile specialists jump, fire elevated themed shots, and defensive enemies retreat',()=>{const {e,p,foe}=arena();foe.kind='thrower';foe.x=p.x+190;foe.cooldown=0;foe.jumpTimer=0;foe.decision=100;e.tick();assert.ok(foe.vz>0);tick(e,40);assert.ok(e.state.shots.some(s=>s.z>34&&s.kind==='arc'));foe.windup=0;foe.defend=1;foe.cooldown=10;const before=foe.x;e.tick();assert.ok(foe.x>before);});

test('moving trap damage follows the visible cart or supported cargo sling',()=>{const C=require('../js/content');for(const kind of ['cart','cargo']){const {e,p}=arena();const trap={x:p.x+100,y:p.y,kind,clock:3.4};e.state.traps=[trap];p.invincible=0;e.state.time=3.4;const area=C.trapArea({...trap,clock:trap.clock+STEP});p.x=area.x;e.tick();assert.ok(p.hp<100);}});

test('projectiles hit standing players at chest height but pass under a high jump',()=>{for(const height of [0,80]){const {e,p,foe}=arena();p.invincible=0;p.z=height;p.vz=0;e.state.shots=[{x:p.x,y:p.y,z:34,vx:0,vy:0,life:1,owner:foe.id}];e.tick();assert.equal(p.hp,height?100:87);}});
test('a thrown prop killing the boss also waits for the complete ending',()=>{const {e,p,boss}=bossFixture(0);boss.hp=1;boss.cooldown=100;boss.superTimer=100;e.state.missiles=[{x:boss.x,y:boss.y,z:20,vx:0,life:1,hits:[],kind:'barrel'}];e.tick();assert.ok(e.state.ending);assert.equal(e.state.status,'playing');tick(e,100);assert.equal(e.state.status,'playing');tick(e,170);assert.equal(e.state.status,'clear');});

test('a diagonal visible at the arena edge cannot lead the player below the locked screen',()=>{const e=createEngine();e.start();for(let i=0;i<3;i++){e.state.status='clear';e.advance();}const p=e.state.players[0];p.x=170;p.invincible=100;e.tick();e.state.traps=[];e.state.props=[];e.state.pickups=[];e.state.enemies.forEach(n=>n.cooldown=100);e.input(0,'right',true);e.input(0,'down',true);for(let i=0;i<700;i++){e.tick();assert.ok(p.y-e.state.cameraY<=487);assert.ok(require('../js/content').walkable(stages[3],p.x,p.y));}});

test('first encounter release pans smoothly without moving the player or snapping to the next arena',()=>{for(const players of [1,2]){const e=createEngine();e.start({players});e.state.players.forEach(p=>{p.x=170;p.invincible=100;});e.tick();e.state.waveCount=1;e.state.players.forEach(p=>p.x=850);const camera=e.state.camera;e.state.enemies=[];e.tick();assert.equal(e.state.camera,camera);const x=e.state.players[0].x;for(let n=0;n<150;n++){const before=e.state.camera;e.tick();assert.ok(e.state.camera-before<=300*STEP+.00001);assert.equal(e.state.players[0].x,x);}assert.ok(e.state.camera>camera+400);assert.equal(e.state.gate,1);assert.equal(e.state.arena,false);}});
test('every ordinary enemy enters from outside view, lands safely and allows pause mid entrance',()=>{const seen=new Set();for(let seed=1;seed<35;seed++){const e=createEngine({seed});e.start({difficulty:'hard'});const p=e.state.players[0];p.x=170;e.tick();e.state.props=[];e.state.traps=[];e.state.pickups=[];const arrivals=e.state.enemies.slice();assert.ok(arrivals.length<=6);for(const foe of arrivals){seen.add(foe.entrance.style);assert.ok(foe.x<e.state.camera-100||foe.x>e.state.camera+1060);}const delays=arrivals.map(f=>f.entrance.delay);assert.equal(new Set(delays).size,delays.length);tick(e,20);e.pause();const before=JSON.stringify(e.state.enemies);tick(e,50);assert.equal(JSON.stringify(e.state.enemies),before);e.pause();tick(e,150);assert.ok(arrivals.every(f=>!f.entrance&&f.x>=e.state.camera&&f.x<=e.state.camera+960));}assert.equal(seen.size,5);});
test('entrances cannot hurt the player, be farmed with specials or release the arena early',()=>{const e=createEngine();e.start();const p=e.state.players[0];p.x=170;e.tick();e.state.traps=[];e.state.props=[];e.state.pickups=[];const foe=e.state.enemies[0];e.state.enemies=[foe];foe.entrance.delay=2;foe.x=p.x+20;foe.y=p.y;p.energy=100;p.invincible=0;const hp=foe.hp;e.input(0,'special',true);tick(e,60);assert.equal(foe.hp,hp);assert.equal(p.hp,100);assert.equal(e.state.arena,true);assert.equal(e.state.gate,0);});

test('entrance shadows follow curved ground and all landings stay on the route',()=>{const C=require('../js/content');for(let index=0;index<6;index++){const e=createEngine();e.start();for(let i=0;i<index;i++){e.state.status='clear';e.advance();}const p=e.state.players[0];e.state.gate=1;p.x=stages[index].encounters[1]-300;e.state.camera=p.x-310;e.state.cameraY=C.floor(stages[index],p.x);p.y=416+e.state.cameraY;p.invincible=100;e.tick();e.state.props=[];e.state.traps=[];for(let n=0;n<120;n++){for(const f of e.state.enemies)if(f.entrance){assert.ok(C.walkable(stages[index],f.entrance.landX,f.entrance.landY));if(f.entrance.announced)assert.ok(Math.abs((f.y-C.floor(stages[index],f.x))-(f.entrance.landY-C.floor(stages[index],f.entrance.landX)))<.001);}e.tick();}}});

test('each era has just three widely separated themed sites, a safe lane and limited props',()=>{const e=createEngine();e.start();const themes=new Set();for(let i=0;i<6;i++){if(i){e.state.status='clear';e.advance();}const s=stages[i],traps=e.state.traps;assert.equal(traps.length,3);assert.equal(new Set(traps.map(t=>t.kind)).size,2);assert.ok(traps[0].x>1500);assert.ok(e.state.props.length<=6);for(const [j,t] of traps.entries()){themes.add(t.kind);assert.ok(s.traps.includes(t.kind));const b=require('../js/content').bounds(s,t.x);assert.ok(b.max-(t.y+27)>=72);assert.equal(require('../js/content').floor(s,t.x-110),require('../js/content').floor(s,t.x+110));if(j)assert.ok(t.x-traps[j-1].x>1700);}}assert.equal(themes.size,12);});
test('traps start quietly on approach, give a full warning and stop when disabled',()=>{const {e,p}=arena();const t={id:88,x:p.x,y:p.y,kind:'steam',clock:0};e.state.traps=[t];p.invincible=0;tick(e,135);assert.equal(p.hp,100);assert.equal(t.active,false);tick(e,10);assert.ok(t.warning);tick(e,45);assert.equal(p.hp,100);tick(e,12);assert.ok(t.active);assert.ok(p.hp<100);t.disabled=true;p.invincible=0;const hp=p.hp;tick(e,90);assert.equal(p.hp,hp);assert.equal(t.active,false);});
test('themed controls, guided objects, and timed console actually neutralize their linked trap',()=>{for(const kind of ['hydrant','cutoff','capstan','slab','winch','brake','valve','console','powder','battery']){const {e,p}=arena();const t={id:444,x:p.x+155,y:p.y-30,kind:kind==='console'?'press':'geyser',clock:0};e.state.traps=[t];e.state.props=[{kind,target:444,x:p.x+40,y:p.y,hp:10}];e.input(0,'attack',true);tick(e,8);e.input(0,'attack',false);tick(e,65);assert.equal(t.disabled,true,kind);if(kind==='slab')assert.equal(t.plugged,true);if(kind==='console'){tick(e,370);assert.equal(t.disabled,false);assert.equal(e.state.props[0].hp,24);assert.ok(!t.active);}}});
test('no entrance landing overlaps a trap hazard lane on any stage',()=>{const C=require('../js/content');for(let stage=0;stage<6;stage++)for(const gate of [2,5,8]){const e=createEngine({seed:4});e.start({difficulty:'hard',players:2});for(let i=0;i<stage;i++){e.state.status='clear';e.advance();}const s=stages[stage];e.state.gate=gate;e.state.camera=s.encounters[gate]-630;e.state.cameraY=C.floor(s,e.state.camera+310);e.state.players.forEach(p=>{p.x=s.encounters[gate]-290;p.y=416+C.floor(s,p.x);});e.tick();assert.ok(e.state.enemies.length>0);for(const foe of e.state.enemies)for(const t of e.state.traps)if(Math.abs(foe.entrance.landX-t.x)<210)assert.ok(Math.abs(foe.entrance.landY-t.y)>=75);}});

test('castle darts require a grounded pressure-tile contact before their warning cycle starts',()=>{const {e,p,foe}=arena();foe.x=p.x+300;foe.stun=100;const t={kind:'darts',x:p.x+120,y:p.y,clock:0};e.state.traps=[t];tick(e,120);assert.equal(t.clock,0);p.x=t.x;p.z=70;p.vz=0;e.tick();assert.equal(t.clock,0);p.z=0;e.tick();assert.ok(t.warning);assert.equal(t.active,false);p.x=t.x-100;tick(e,250);assert.equal(t.clock,0);assert.equal(t.active,false);});
