'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createEngine,stages,STEP}=require('../js/engine');
const tick=(e,n)=>{for(let i=0;i<n;i++)e.tick();};
function arena(options={}){const e=createEngine({seed:42});e.start(options);e.state.players[0].x=160;e.tick();e.state.props=[];e.state.enemies=e.state.enemies.slice(0,1);const foe=e.state.enemies[0];Object.assign(foe,{kind:'grunt',x:225,y:416,hp:200,maxHp:200,cooldown:100,stun:0,down:0});e.state.players[0].invincible=100;return {e,p:e.state.players[0],foe};}
test('six eras each have a distinct theme, boss, and collectible weapon',()=>{assert.equal(stages.length,6);for(const key of ['theme','boss','weapon'])assert.equal(new Set(stages.map(s=>s[key])).size,6);});
test('start and restart honor difficulty, co-op and a reproducible seed',()=>{const e=createEngine({seed:17});e.start({players:2,difficulty:'hard'});assert.equal(e.state.players.length,2);assert.equal(e.state.players[0].lives,2);e.state.score=999;e.start({difficulty:'easy'});assert.equal(e.state.score,0);assert.equal(e.state.players[0].lives,5);});
test('movement uses a bounded ground plane without treating up as climbing',()=>{const {e,p}=arena();e.input(0,'up',true);tick(e,150);assert.equal(p.y,335);assert.equal(p.z,0);e.input(0,'up',false);e.input(0,'down',true);tick(e,150);assert.equal(p.y,487);assert.equal(p.z,0);});
test('a quick released Jump automatically delivers an airborne kick and lands',()=>{const {e,p,foe}=arena();e.input(0,'jump',true);e.input(0,'jump',false);tick(e,13);assert.ok(p.z>30);assert.ok(foe.hp<200);assert.equal(p.action.kind,'kick');tick(e,65);assert.equal(p.z,0);assert.equal(p.vz,0);});
test('holding Jump cannot repeatedly hop after landing',()=>{const {e,p}=arena();e.input(0,'jump',true);tick(e,150);assert.equal(p.z,0);assert.equal(e.drainEvents().filter(x=>x.type==='jump').length,1);});
test('held Attack chains three hits with a finishing knockdown, not per-frame damage',()=>{const {e,p,foe}=arena();e.input(0,'attack',true);tick(e,50);assert.equal(p.comboStep,3);assert.equal(foe.hp,156);assert.ok(foe.down>0);assert.equal(e.state.combo,3);});
test('attacks miss enemies in another depth lane',()=>{const {e,foe}=arena();foe.y=480;e.input(0,'attack',true);tick(e,8);assert.equal(foe.hp,200);});
test('a vulnerable close enemy is thrown and damages another even if the throw kills it',()=>{const {e,p,foe}=arena();foe.x=p.x+25;foe.hp=15;const other={...foe,id:999,x:p.x+95,hp:100,maxHp:100,throwHits:[]};e.state.enemies.push(other);e.input(0,'attack',true);tick(e,18);assert.ok(foe.hp<=0);assert.ok(other.hp<100);assert.ok(e.drainEvents().some(x=>x.type==='throw'));});
test('bosses cannot be grabbed and thrown',()=>{const {e,p,foe}=arena();foe.boss=true;foe.hp=15;foe.x=p.x+25;e.input(0,'attack',true);tick(e,8);assert.ok(!e.drainEvents().some(x=>x.type==='throw'));});
test('boss windups survive player combos and still resolve an attack',()=>{const {e,p,foe}=arena();p.invincible=0;foe.boss=true;foe.x=p.x+45;foe.cooldown=0;e.input(0,'attack',true);tick(e,70);assert.ok(p.hp<100);assert.ok(foe.hp<200);});
test('special requires charge, hits its area and is consumed once per press',()=>{const {e,p,foe}=arena();p.energy=99;e.input(0,'special',true);tick(e,1);assert.equal(foe.hp,200);e.input(0,'special',false);p.energy=100;e.input(0,'special',true);tick(e,15);assert.equal(foe.hp,158);assert.ok(p.energy<100);assert.equal(e.drainEvents().filter(x=>x.type==='special').length,1);});
test('breakable props yield actual healing and weapon pickups with limited durability',()=>{const {e,p}=arena();e.state.props=[{id:20,x:p.x+40,y:p.y,hp:10,kind:'food'}];e.input(0,'attack',true);tick(e,8);assert.equal(e.state.props[0].hp<=0,true);assert.equal(e.state.pickups.length,1);e.input(0,'attack',false);p.hp=50;p.x+=40;tick(e,5);assert.equal(p.hp,85);e.state.pickups=[{x:p.x,y:p.y,kind:'weapon'}];tick(e,1);assert.equal(p.weapon,stages[0].weapon);assert.equal(p.weaponHits,18);});
test('enemy windup is visible before damage, and a jump dodges a ground strike',()=>{const {e,p,foe}=arena();p.invincible=0;foe.cooldown=0;foe.x=p.x+45;tick(e,1);assert.ok(foe.windup>0);assert.equal(p.hp,100);e.input(0,'jump',true);tick(e,30);assert.equal(p.hp,100);});
test('taking damage respawns locally, exhausted lives lead to gameover, continues are limited',()=>{const {e,p,foe}=arena();p.lives=1;p.hp=1;p.invincible=0;foe.x=p.x+45;foe.cooldown=0;tick(e,125);assert.equal(e.state.status,'gameover');assert.equal(p.lives,0);e.continueRun();assert.equal(e.state.status,'playing');assert.equal(e.state.continues,1);assert.equal(p.hp,100);e.state.status='gameover';e.continueRun();e.state.status='gameover';e.continueRun();assert.equal(e.state.status,'gameover');assert.equal(e.state.continues,0);});
test('pause clears pending input and freezes all combat state',()=>{const {e,p}=arena();e.input(0,'jump',true);e.pause();const before=JSON.stringify(e.state);tick(e,50);assert.equal(JSON.stringify(e.state),before);e.pause();tick(e,1);assert.equal(p.z,0);});
test('one co-op player can be out while the other continues fighting',()=>{const {e,p}=arena({players:2});p.lives=0;p.dead=0;tick(e,1);assert.equal(e.state.status,'playing');assert.equal(e.state.players[1].hp,100);});
test('sixty encounters, eighteen ambushes and six bosses advance to victory',()=>{const e=createEngine();e.start();let bosses=0,ambushes=0;for(let stage=0;stage<6;stage++){assert.equal(e.state.stage,stage);for(let gate=0;gate<stages[stage].encounters.length;gate++){e.state.players[0].x=stages[stage].encounters[gate]-300;e.tick();assert.equal(e.state.arena,true);bosses+=e.state.enemies.filter(x=>x.boss).length;e.state.enemies.forEach(x=>{x.hp=0;x.dead=0;});e.tick();if(e.state.wave===1){ambushes++;e.state.enemies.forEach(x=>{x.hp=0;x.dead=0;});e.tick();}assert.equal(e.state.gate,gate+1);}assert.equal(e.state.status,'clear');e.advance();}assert.equal(bosses,6);assert.equal(ambushes,18);assert.equal(e.state.status,'victory');});
test('all six eras can be fought to victory with real inputs and finite player health',()=>{const e=createEngine({seed:5});e.start({difficulty:'normal'});for(let i=0;i<300000&&!['gameover','victory'].includes(e.state.status);i++){
  if(e.state.status==='clear'){e.advance();continue;}
  const p=e.state.players[0],enemies=e.state.enemies.filter(x=>x.hp>0),target=enemies.sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];
  const dx=target?target.x-p.x:100,dy=target?target.y-p.y:0;
  e.input(0,'right',dx>40||(!target));e.input(0,'left',dx< -40);e.input(0,'up',dy< -8);e.input(0,'down',dy>8);e.input(0,'attack',true);e.input(0,'jump',!!target&&i%70===0);e.input(0,'special',p.energy>=100&&!!target);e.tick();
}assert.equal(e.state.status,'victory',JSON.stringify({status:e.state.status,gate:e.state.gate,player:e.state.players[0],enemies:e.state.enemies}));assert.ok(e.state.kills>=90);});
test('identical seed and input sequence reproduce combat results',()=>{function run(){const e=createEngine({seed:7});e.start();for(let i=0;i<900;i++){e.input(0,'right',i<150);e.input(0,'attack',i>90);e.input(0,'jump',i%90===0);e.tick(STEP);}return {score:e.state.score,players:e.state.players,enemies:e.state.enemies,hash:e.hash()};}assert.deepEqual(run(),run());});

test('every route exceeds Commando length with varied encounter spacing and seven landmarks',()=>{
  for(const s of stages){assert.ok(s.width>6600);assert.equal(s.encounters.length,10);assert.equal(s.landmarks.length,7);assert.equal(new Set(s.landmarks).size,7);assert.ok(new Set(s.encounters.slice(1).map((x,i)=>x-s.encounters[i])).size>3);assert.ok(s.encounters.at(-1)+350<s.width);}
});
test('a continue resumes at the latest supply checkpoint with clean combat state',()=>{
  const e=createEngine();e.start();const p=e.state.players[0];e.state.gate=2;p.x=stages[0].encounters[2]-300;e.tick();p.hp=30;
  for(let i=0;i<2;i++){e.state.enemies=[];e.tick();}assert.equal(e.state.checkpoint,3);assert.equal(p.hp,75);
  e.state.status='gameover';e.state.hazards=[{kind:'steam'}];e.continueRun();assert.equal(e.state.gate,3);assert.equal(e.state.hazards.length,0);assert.equal(p.hp,100);assert.ok(p.x>2000);assert.ok(e.state.camera>0);assert.ok(e.state.props.every(prop=>prop.x>=p.x));
});
function bossFixture(index){const e=createEngine();e.start();for(let i=0;i<index;i++){e.state.status='clear';e.advance();}e.state.gate=9;const p=e.state.players[0];p.x=stages[index].encounters[9]-300;p.invincible=100;e.tick();const boss=e.state.enemies.find(x=>x.boss);e.state.enemies=[boss];boss.superTimer=0;boss.cooldown=0;return {e,p,boss};}
test('each boss telegraphs a distinct superpower that resolves even from across the arena',()=>{
  const kinds=[];for(let stage=0;stage<6;stage++){const {e,p,boss}=bossFixture(stage);e.tick();assert.equal(boss.attack.kind,'super');assert.ok(boss.windup>=1);assert.equal(e.state.hazards.length,0);tick(e,67);assert.ok(e.state.hazards.length>=2);assert.ok(e.state.hazards.every(h=>h.delay>0));assert.equal(p.hp,100);kinds.push(e.state.hazards[0].kind);boss.hp=0;e.tick();assert.equal(e.state.hazards.length,0);}assert.equal(new Set(kinds).size,6);
});
test('red rage phase starts at thirty percent, persists and accelerates recovery',()=>{
  const {e,boss}=bossFixture(0);boss.superTimer=100;boss.cooldown=2;boss.hp=boss.maxHp*.31;e.tick();assert.equal(boss.enraged,false);boss.hp=boss.maxHp*.3;e.tick();assert.equal(boss.enraged,true);assert.ok(boss.superTimer<=1);assert.equal(e.drainEvents().filter(x=>x.type==='enrage').length,1);const before=boss.cooldown;e.tick();assert.ok(before-boss.cooldown>STEP);assert.equal(e.drainEvents().filter(x=>x.type==='enrage').length,0);
});
test('superpower damage respects warnings, depth, jumping and player invulnerability',()=>{
  for(const stage of [0,1,2,3,4,5]){const {e,p,boss}=bossFixture(stage);e.tick();tick(e,67);boss.cooldown=100;boss.windup=0;boss.attack=null;boss.superTimer=100;
    const h=e.state.hazards[0];e.state.hazards=[h];h.delay=0;h.vx=0;if(h.kind==='time'){p.x=h.x+29;p.y=h.y;}else{p.x=h.x;p.y=h.y;}p.invincible=0;p.z=0;e.tick();assert.ok(p.hp<100,'damage '+h.kind);const hp=p.hp;e.tick();assert.equal(p.hp,hp,'invulnerability '+h.kind);
  }
  const {e,p,boss}=bossFixture(2);e.tick();tick(e,67);boss.cooldown=100;const h=e.state.hazards[0];e.state.hazards=[h];h.delay=0;h.vx=0;p.x=h.x;p.y=h.y;p.invincible=0;p.z=70;p.vz=0;e.tick();assert.equal(p.hp,100,'jump dodges quake');
});
